### ISSUE TITLE
new version 1.17.0 available

### ISSUE THREAD

**Issue by Flo354** [webjars/jquery-validation#12]
Hi,

There is a new version available. Could you package it?

Thanks,

**Comment by ngocdaothanh** [comment]
Hi can you release 1.17.0 for bower?

When searching https://www.webjars.org, I see this:

```
"org.webjars.bower" % "jquery-validation" % "1.16.0"
```

**Comment by jamesward** [comment]
You can release Bower WebJars on your own via https://www.webjars.org

**Comment by ngocdaothanh** [comment]
Thanks for the instruction 👍
