### ISSUE TITLE
localization messages are not included in the webjar

### ISSUE THREAD

**Issue by lynnboy** [webjars/jquery-validation#13]
Websites always require localized messages

**Comment by jamesward** [comment]
This WebJar includes everything in the upstream's `dist` dir.  Does that dir not contain what you need?

**Comment by lynnboy** [comment]
No, there is a directory named `localization` which contains `messages_XX.js` files and not included in the WebJar.

**Comment by jamesward** [comment]
I'm not seeing that: https://github.com/jquery-validation/jquery-validation/tree/1.17.0/dist

**Comment by lynnboy** [comment]
I'm sorry. They are included in the downloadable release zip package, and are also included on CDNs.
I examined the `Gruntfile.js`, the task `copy` which belongs to the `default` build procedure actually copies `src/localization` to `dist/localization`.
My suggestion is at least include the `localization` directory into the webjar too.

**Comment by jamesward** [comment]
Check out: https://github.com/jquery-validation/jquery-validation/issues/2040
So they have a different zip which has the right stuff.  I'll update the WebJar and perform a new release.

**Comment by jamesward** [comment]
This will be released shortly as `1.17.0-1`
