### ISSUE TITLE
Upper bound on jquery dependency not tight enough

### ISSUE THREAD

**Issue by paddymahoney** [webjars/jquery-validation#7]
<dependencies>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>jquery</artifactId>
                <version>[1.9.1,)</version>
            </dependency>
        </dependencies>

This dependency bound causes jquery-validation to bring in jquery 3.0.0-alpha1 (afaict, this version of jquery breaks jquery-validation, whereas 1.9.1 - 2.1.4 leave it working). 

Could the version bounds be tightened here? Specifying 1.9.1 would produce the desired effect here. Putting an upper bound on the major version of 2 would work (for me) as well. 

Note to others: 
- resolved this problem using sbt's dependencyOverrides - 
    dependencyOverrides += "org.webjars" % "jquery" % "2.1.4"

**Comment by jamesward** [comment]
Can you send a pull request with a good fix?

**Comment by jamesward** [comment]
Fixed by #8
